### ISSUE TITLE
wma playback

### ISSUE THREAD

**Issue by Demon000** [csolanol/device_xiaomi_libra#10]

**Comment by Demon000** [comment]
@csolanol, add `<MediaCodec name="OMX.ffmpeg.wma.decoder" type="audio/x-ms-wma" />` under `<!-- Audio Software  -->` in media_codecs.xml, right under the flac decoder.

**Comment by Demon000** [comment]
@AndropaX

**Comment by csolanol** [comment]
https://github.com/csolanol/device_xiaomi_libra/commit/2ef86a4cedb36c065b31baadf84bdc5cdb559a9a
