### ISSUE TITLE
Swith to LineageOS kernel

### ISSUE THREAD

**Issue by dtritus** [csolanol/device_xiaomi_libra#21]
I suggest to change dependency to [LineageOS kernel](https://github.com/LineageOS/android_kernel_xiaomi_msm8992).
This will simplify maintenance, you will not need to switch branches of @Demon000 kernel repo (currently it's `cm-14.1-mike`).

**Comment by Demon000** [comment]
:+1:

**Comment by csolanol** [comment]
done
