### ISSUE TITLE
Video recording stops at 30 seconds

### ISSUE THREAD

**Issue by Demon000** [csolanol/device_xiaomi_libra#5]

**Comment by Hikari-no-Tenshi** [comment]
Revert commit https://github.com/AICP/frameworks_av/commit/22b539295a3f34056b15adb094faccd56104d335

**Comment by Demon000** [comment]
Thanks Hikari! Will try tomorrow.

**Comment by csolanol** [comment]
Thanks Hikari!

**Comment by csolanol** [comment]
https://github.com/csolanol/device_xiaomi_libra/commit/9a1834c9cc1894b63f3d6538636adcb3a280a77f
