### ISSUE TITLE
Encryption stop device from booting

### ISSUE THREAD

**Issue by null-von-sushi** [csolanol/device_xiaomi_libra#9]
Formatted /system and /data
Installed `aicp_libra_n-12.1-NIGHTLY-20170309.zip`
Booted Phone
Rebooted Phone
Set Screen lock
Tapped on 'encrypt device' under security
Device restarts and get's stuck in a 'bootloop', however not the Android one (where you can see the bootanimation of AICP, but the Xiaomi brand one that appears for a few seconds when power on the device.

From this point onwards the device just turns on, gets stuck on "Mi | mi.com" for a about 8 seconds, turns off and then turns back on again, only to get stuck again.

**Comment by xinomilo** [comment]
had the same thing with 20170313 rom. 
logcat : 
03-16 20:48:18.027   353   434 E Cryptfs : keymaster_create_key failed
03-16 20:48:18.027   353   434 E Cryptfs : Cannot create encrypted master key
03-16 20:48:18.027   353   434 E Cryptfs : Error enabling encryption after framework is shutdown, no data changed, restarting system

stuck on the Xiaomi brand and a rebooting loop like described above. had to boot into recovery and wipe data partition to boot to rom.
